# Base CAARMA config for the original clean training entrypoint (`train.py`).
model: "MFA-CONFORMER" #"ECAPA" #"MFA-CONFORMER" #ECAPA, MFA-CONFORMER, RAWNET3, SKA_TDNN, ECAPA-LARGE etc. (Add)
features: "FBank_New" #FBank, MFCC SpeechTokenizer, FBank_New, waveform, featNone
augmentations: {
  add_noise: False,
  add_reverb: False,
  drop_freq: False,
  drop_chunk: False,

}
dataset: null
vox1_wav_root: "/ocean/projects/cis220031p/shared/raw/data/VoxCeleb1/wav"
vox1_split_dir: "/ocean/projects/cis220031p/shared/raw/data/VoxCeleb1/data"
train_split_csv: "/ocean/projects/cis220031p/shared/raw/data/VoxCeleb1/data/vox1_train.csv"
val_split_csv: "/ocean/projects/cis220031p/shared/raw/data/VoxCeleb1/data/vox1_val.csv"
test_split_csv: "/ocean/projects/cis220031p/shared/raw/data/VoxCeleb1/data/vox1_test.csv"
active_split: "train"
USE_WANDB: True 
criterion: 'AMSoftmaxGAN' #'AMSoftmaxGAN' #'AMSoftmaxGAN' #'Softmax' #'AMSoftmax'
init_lr: 0.001
epochs: 30 
weight_decay: 0.0000001 
trial_path: "./data/vox1_test.txt"
root: "./voxceleb1_test/wav/"
warmup_step: 2000
batch_size: 200
num_workers: 40
second: 3
do_augmentation: False
num_spk: 7323
mixup: True
embedding_dim: 192 
checkpoint_path: "None" 
save_dir: "caarma_mfa_ckpts" 
title: "caarma_mfa"  


# ECAPA-LARGE WAS USED
